### PR TITLE
fix(style): gist style improvements

### PR DESCRIPTION
**Pull request by sheldonhull**
fix(style): remove whitespace setting to preserve gist indentation

- The setting white-space: nowrap; strips indentation resulting in poor gist rendering. This removal should resolve that

fix(style): improve gist markdown file rendering

- Background now correctly uses the theme default, allowing render of markdown to be seamless.
- #TODO: Nested code highlights from the markdown file itself still don't render with theming correctly. Could use help on this if it's possible to use the recursion on styles to apply to the gist contents. Not sure.

### CODE REVIEW

**Comment by sheldonhull** [comment]
To see how this currently renders with no fixes: [link](https://www.sheldonhull.com/docs/powershell/#syncing-files-using-s5cmd).

This should show you the background of the markdown file is white, despite being dark theme.
The fixes applied improve the markdown rendering to reflect theme color so it's more "inline" and less obvious that the markdown content rendered is from a gist.

As mentioned the code snippets embedded in the gist itself don't honor the syntax highlight so I'm not certain if it's possible to recursively update this.

**Comment by sheldonhull** [comment]
@victor-pogor mind looking at this? The whitespace fix would be useful for those embedding gists and wanting to preserve indentation.

**Comment by victor-pogor** [comment]
Hi @sheldonhull 

I agree about `white-space` and the indentation issue.

But I don't understand about background and syntax highlighting issue. I see that the background color is set based on theme color. Can you provide more details on what is expected behavior?

Thanks.

image
image

**Comment by sheldonhull** [comment]
@victor-pogor the formatting is for embedded `MARKDOWN`. 
If you embed a gist that has embedded markdown you'll find the background doesn't honor the dark/light theme. 
This was the fix I attempted to provide for one small step towards this.

**Comment by sheldonhull** [comment]
@victor-pogor here's a refreshed copy to show you what I mean:

The embedded markdown background in my customized version matches theme. 
The code syntax still doesn't, but it's a step foward at least. 

The embedded file you see is `README.md` which has problems with inheriting the default markdown theme, instead using gist specific formatting. This is a multifile gist you could test embedding.

image

[Link showing how this renders on my site currently](https://www.sheldonhull.com/docs/go/#logging)

[Finally the gist link](https://gist.github.com/sheldonhull/9e608da09f84fac600d921e3f0867226)

**Comment by victor-pogor** [comment]
Oh, I see. Thank you for the explanations. Let me check if it will be possible to preserve the original style to the nested markdown code.

**Comment by victor-pogor** [comment]
Sorry for the delay. I had busy days. Still investigating...

**Comment by victor-pogor** [comment]
Hi @sheldonhull. What do you think about this?

image

image

The changed code looks like this:

```diff
code,
pre,
.highlight table,
.highlight tr,
.highlight td {
-  background: $code-background-color;
+  background: $code-background-color !important;

  [theme="dark"] & {
-    background: $code-background-color-dark;
+    background: $code-background-color-dark !important;
  }
}

/* Other styles */

.gist {
  .gist-file,
  .gist-data,
  .gist-meta {
-    border:none
+    background: none;
  }

+  .gist-file {
+    border-color: $global-font-secondary-color;

+    [theme="dark"] & {
+      border-color: $global-font-secondary-color-dark;
+    }
  }

  .gist-meta {
    padding: 0.4rem 0.8rem;
    background-color: darken($code-background-color, 5%);

    @include link(false, false);

    [theme="dark"] & {
      background-color: darken($code-background-color-dark, 5%);
    }
  }

+  color: $global-font-color;

  [theme="dark"] & {
+    color: $global-font-color-dark;

    // imported from https://github.com/lonekorean/gist-syntax-themes/blob/master/stylesheets/one-dark.css
    .highlight {
-      background: #141414;
+      background: none;
    }

/* Other styles  */
```

**Comment by sheldonhull** [comment]
Much better! Thank you! Ship it! 🚀🚀🚀

**Comment by victor-pogor** [comment]
I've created a new PR for this. Your commit history has been preserved. I appreciate your work 👍 

@all-contributors please add @sheldonhull for bug

**Pull request closed without merging**
